/**
 * Sentinel configuration for pi-zep.
 *
 * Both steps mirror exactly what CI runs, so a green turn means a green
 * pipeline. They are declared explicitly rather than relying on the built-in
 * `npx --no-install tsc --noEmit` step so the type-check runs against the same
 * `include` set as `npm run typecheck` and is judged on precisely the files it
 * can speak about.
 */

export default {
  pipelines: {
    onFileMutation: [
      {
        name: "type-check",
        cmd: "npm run typecheck",
        timeoutMs: 30000,
        // Matches `include` in tsconfig.json, so edits to package.json,
        // .npmrc or the workflows do not trigger a full type-check.
        files: [
          "index.ts",
          "src/**/*.ts",
          "tests/**/*.ts",
          "scripts/**/*.ts",
          "sentinel.config.ts",
        ],
        priority: "critical",
        cacheable: false,
      },
    ],

    onTurnEnd: [
      {
        name: "unit-tests",
        cmd: "npm test",
        timeoutMs: 60000,
        files: ["index.ts", "src/**/*.ts", "tests/**/*.ts"],
        // ~0.2s and deterministic, so a cached verdict buys nothing worth the
        // risk of serving an outdated green. The suite runs on Node 22 and 26
        // (see the CI matrix); it touches no network - fetch is stubbed - so it
        // is safe to run on every turn.
        priority: "critical",
        cacheable: false,
      },
    ],
  },

  // `exclude` replaces the built-in list, so the defaults are repeated here.
  // graph-out/** is generated by pi-mindplace; regenerating the graph must not
  // count as a source mutation. README.md is documentation only.
  exclude: [
    "**/node_modules/**",
    "**/.git/**",
    "**/*.md",
    "dist/**",
    "graph-out/**",
  ],
};
